version: "3"

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=engine
    ports:
      - 5432:5432
